AWSTemplateFormatVersion: 2010-09-09
Resources:
  AGRA1HUD6:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: ercot_load_forecast
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
  AGRV2WX5K:
    Type: 'AWS::ApiGateway::RequestValidator'
    Properties:
      RestApiId: !Ref AGRA1HUD6
      ValidateRequestBody: false
      ValidateRequestParameters: true
  AGM84WK:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      ApiKeyRequired: true
      AuthorizationType: NONE
      HttpMethod: GET
      RequestValidatorId: !Ref AGRV2WX5K
      Integration:
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates: {}
            StatusCode: '200'
        PassthroughBehavior: WHEN_NO_MATCH
        RequestParameters:
          integration.request.querystring.delivery_date: method.request.querystring.delivery_date
        RequestTemplates:
          application/json: |
            {
                 "delivery_date": "$input.params('delivery_date')"
            }
        TimeoutInMillis: 29000
        Type: AWS
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:26982295****:function:api_ercot_load_forecast/invocations
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          StatusCode: '200'
      RequestParameters:
        method.request.querystring.delivery_date: true
      ResourceId: !GetAtt 
        - AGRA1HUD6
        - RootResourceId
      RestApiId: !Ref AGRA1HUD6
  LPT3S5:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: api_ercot_load_forecast
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Join':
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':execute-api:'
            - !Ref 'AWS::Region'
            - ':'
            - !Ref 'AWS::AccountId'
            - ':'
            - !Ref AGRA1HUD6
            - /*/GET/